/**
 * @file kem.c
 * @author Alex Anderson (aandrs@vt.edu)
 * @brief FrodoKEM-1344-AES Key Encapsulation Mechanism
 * @version 0.1
 * @date 2026-04-12
 *
 * Implements Frodo.KeyGen, Frodo.Encaps, Frodo.Decaps for FrodoKEM-1344-AES.
 *
 * @note Porting to TM4C123GH6PM and TM4C1294NCPDT microcontrollers
 * @note Large buffers are declared `static` to avoid stack issues on embedded
 * platforms
 * @note Verified against NIST KAT vectors (newer_PQCkemKAT_43088.rsp) with
 * 100/100 passed
 *
 * @see FrodoKEM Preliminary Standardization Proposal
 * @see https://frodokem.org
 *
 * @copyright Copyright (c) 2026
 */
#include "../include/frodo_internal.h"
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/**
 * @brief Generate a FrodoKEM-1344-AES public/secret keypair.
 *
 * Implements Frodo.KeyGen per Section 8.1 of the FrodoKEM.
 *
 * @param pk Output public key (size: FRODO_PK_BYTES bytes)
 * @param sk Output secret key (size: FRODO_SK_BYTES bytes)
 *
 * @note Public Key = Seed A || b
 * @note Secret Key = Seed s || Public Key || S^T || Public Key Hash
 *
 * @note 0x5F is the domain separation byte for Frodo.KeyGen (Section 8.1)
 * @note S^T is packed little-endian per Section 8.1, Step 10
 * @note Large matrices are declared `static` to avoid stack overflow on
 * embedded target platforms
 * @warning Not re-entrant due to static buffers
 */
void frodo_keygen(uint8_t *pk, uint8_t *sk) {

    /* Small buffers for random + known values safe for embedded systems */
    uint8_t s[FRODO_SEC_BYTES];
    uint8_t seed_se[FRODO_SE_BYTES];
    uint8_t z[FRODO_SEED_A_BYTES];
    uint8_t seed_A[FRODO_SEED_A_BYTES];
    uint8_t pkh[FRODO_SEC_BYTES];
    uint8_t domain_sep[1 + FRODO_SE_BYTES];
    uint8_t randomness[FRODO_SEC_BYTES + FRODO_SE_BYTES + FRODO_SEED_A_BYTES];
    size_t i, j;

    /* Large buffers, declared static to avoid stack overflows on embedded
     * devices */
    static uint8_t r_buf[2 * FRODO_N * FRODO_NBAR * 2 + 1];
    static uint16_t r_words[2 * FRODO_N * FRODO_NBAR];
    static uint16_t ST[FRODO_NBAR * FRODO_N];
    static uint16_t S[FRODO_N * FRODO_NBAR];
    static uint16_t E[FRODO_N * FRODO_NBAR];
    static uint16_t B[FRODO_N * FRODO_NBAR];
    static uint8_t packed_B[FRODO_PACKED_B_BYTES];
    static uint8_t packed_ST[FRODO_PACKED_B_BYTES];

    /* Generate and parse randomness for seed values */
    randombytes(randomness, sizeof(randomness));
    memcpy(s, randomness, FRODO_SEC_BYTES);
    memcpy(seed_se, randomness + FRODO_SEC_BYTES, FRODO_SE_BYTES);
    memcpy(z, randomness + FRODO_SEC_BYTES + FRODO_SE_BYTES, FRODO_SEED_A_BYTES);
    memset(randomness, 0,
           sizeof(randomness)); // Zero-out randomly generated bytes

    /* Generate Seed_A */
    frodo_shake256(seed_A, FRODO_SEED_A_BYTES, z, FRODO_SEED_A_BYTES);

    /* Generate pseudorandom bit string r */
    domain_sep[0] = 0x5F;
    memcpy(domain_sep + 1, seed_se, FRODO_SE_BYTES);
    frodo_shake256(r_buf, sizeof(r_words), domain_sep, sizeof(domain_sep));

    for (i = 0; i < 2 * FRODO_N * (size_t)FRODO_NBAR; i++) {
        r_words[i] = (uint16_t)r_buf[2 * i] | ((uint16_t)r_buf[2 * i + 1] << 8);
    }

    /* Generate error matrices S^T and E */
    frodo_sample_matrix(ST, r_words, FRODO_NBAR * FRODO_N);
    frodo_sample_matrix(E, r_words + FRODO_NBAR * FRODO_N, FRODO_N * FRODO_NBAR);

    // Transpose ST to get matrix S
    for (i = 0; i < FRODO_N; i++) {
        for (j = 0; j < FRODO_NBAR; j++) {
            S[i * FRODO_NBAR + j] = ST[j * FRODO_N + i];
        }
    }

    /* Compute matrix B (A*S+E) */
    frodo_compute_b(B, S, E, seed_A);

    /* Convert matrix B into a byte array */
    frodo_pack(packed_B, FRODO_PACKED_B_BYTES, B, FRODO_N * FRODO_NBAR);

    /* Return public key (pk) + secret key (sk) */

    // PUBLIC KEY
    memcpy(pk, seed_A, FRODO_SEED_A_BYTES);
    memcpy(pk + FRODO_SEED_A_BYTES, packed_B, FRODO_PACKED_B_BYTES);

    /* Compute Public Key Hash (pkh) */
    frodo_shake256(pkh, FRODO_SEC_BYTES, pk, FRODO_PK_BYTES);

    // SECRET KEY
    frodo_pack_le16(packed_ST, ST,
                    FRODO_NBAR * FRODO_N); // little-endian for sk
    memcpy(sk, s, FRODO_SEC_BYTES);
    memcpy(sk + FRODO_SEC_BYTES, pk, FRODO_PK_BYTES);
    memcpy(sk + FRODO_SEC_BYTES + FRODO_PK_BYTES, packed_ST, FRODO_PACKED_B_BYTES);
    memcpy(sk + FRODO_SEC_BYTES + FRODO_PK_BYTES + FRODO_PACKED_B_BYTES, pkh, FRODO_SEC_BYTES);

    /* Zeroize sensitive intermediate values */
    memset(s, 0, sizeof(s));
    memset(seed_se, 0, sizeof(seed_se));
    memset(ST, 0, sizeof(ST));
    memset(S, 0, sizeof(S));
    memset(E, 0, sizeof(E));
    memset(r_buf, 0, sizeof(r_buf));
}

/**
 * @brief Encapsulate a shared secret using a public key.
 *
 * Implements Frodo.Encaps per Section 8.2 of the FrodoKEM specification.
 *
 * @param ct Output Ciphertext (size: FRODO_CT_BYTES bytes)
 * @param ss Output Shared secret (size: FRODO_SS_BYTES bytes)
 * @param pk Input Public key (size: FRODO_PK_BYTES bytes)
 *
 * @note 0x96 is the domain separation byte for Encaps per Section 8.2
 * @note Large buffers are static to avoid stack overflow issues on embedded
 * devices
 */
void frodo_encaps(uint8_t *ct, uint8_t *ss, const uint8_t *pk) {

    /* Parse seed_A and packed_B from pk */
    const uint8_t *seed_A   = pk;
    const uint8_t *packed_B = pk + FRODO_SEED_A_BYTES;

    /* Small buffers - safe for the stack */
    uint8_t randomness[FRODO_SEC_BYTES + FRODO_SALT_BYTES];
    uint8_t u[FRODO_SEC_BYTES];
    uint8_t salt[FRODO_SALT_BYTES];
    uint8_t pkh[FRODO_SEC_BYTES];
    uint8_t digest[FRODO_SE_BYTES + FRODO_SEC_BYTES];
    uint8_t shake_in[FRODO_SEC_BYTES + FRODO_SEC_BYTES + FRODO_SALT_BYTES];
    uint8_t domain_sep[1 + FRODO_SE_BYTES];
    uint8_t packed_C[FRODO_PACKED_C_BYTES];
    uint16_t Epp[FRODO_NBAR * FRODO_NBAR];
    uint16_t V[FRODO_NBAR * FRODO_NBAR];
    uint16_t C[FRODO_NBAR * FRODO_NBAR];
    uint16_t encoded_u[FRODO_NBAR * FRODO_NBAR];
    size_t i;

    /* Pointers into digest for seed_se and k */
    uint8_t *seed_se = digest;
    uint8_t *k       = digest + FRODO_SE_BYTES;

    /* Large buffers - static to keep them off the stack */
    static uint8_t r_buf[(2 * FRODO_N * FRODO_NBAR + FRODO_NBAR * FRODO_NBAR) * 2];
    static uint16_t r_words[2 * FRODO_N * FRODO_NBAR + FRODO_NBAR * FRODO_NBAR];
    static uint16_t Sp[FRODO_NBAR * FRODO_N];
    static uint16_t Ep[FRODO_NBAR * FRODO_N];
    static uint16_t Bp[FRODO_NBAR * FRODO_N];
    static uint16_t B[FRODO_N * FRODO_NBAR];
    static uint8_t packed_Bp[FRODO_PACKED_B_BYTES];
    static uint8_t
        ss_in[FRODO_PACKED_B_BYTES + FRODO_PACKED_C_BYTES + FRODO_SALT_BYTES + FRODO_SEC_BYTES];

    /* Sample: u || salt */
    randombytes(randomness, sizeof(randomness));
    memcpy(u, randomness, FRODO_SEC_BYTES);
    memcpy(salt, randomness + FRODO_SEC_BYTES, FRODO_SALT_BYTES);
    memset(randomness, 0, sizeof(randomness));

    /* Compute: pkh <- SHAKE256(pk) */
    frodo_shake256(pkh, FRODO_SEC_BYTES, pk, FRODO_PK_BYTES);

    /* Arrange: pkh || u || salt */
    memcpy(shake_in, pkh, FRODO_SEC_BYTES);
    memcpy(shake_in + FRODO_SEC_BYTES, u, FRODO_SEC_BYTES);
    memcpy(shake_in + FRODO_SEC_BYTES + FRODO_SEC_BYTES, salt, FRODO_SALT_BYTES);

    /* Compute: seed_se || k <- SHAKE256(pkh || u || salt) */
    frodo_shake256(digest, sizeof(digest), shake_in, sizeof(shake_in));

    /* Arrange: 0x96 (domain separation byte) || seed_se */
    domain_sep[0] = 0x96;
    memcpy(domain_sep + 1, seed_se, FRODO_SE_BYTES);

    /* Compute: r <- SHAKE256(0x96 || seed_se) */
    frodo_shake256(r_buf, sizeof(r_buf), domain_sep, sizeof(domain_sep));

    /* Convert: r bytes -> little-endian uint16_t words */
    for (i = 0; i < 2 * FRODO_N * FRODO_NBAR + FRODO_NBAR * FRODO_NBAR; i++) {
        r_words[i] = (uint16_t)r_buf[2 * i] | ((uint16_t)r_buf[2 * i + 1] << 8);
    }

    /* Sample: matrices S', E', and E'' */
    frodo_sample_matrix(Sp, r_words, FRODO_NBAR * FRODO_N);
    frodo_sample_matrix(Ep, r_words + FRODO_NBAR * FRODO_N, FRODO_NBAR * FRODO_N);
    frodo_sample_matrix(Epp, r_words + 2 * FRODO_NBAR * FRODO_N, FRODO_NBAR * FRODO_NBAR);

    /* Compute: B' <- (S' * A + E') */
    frodo_mul_add_spa_plus_e(Bp, Sp, Ep, seed_A);

    /* Convert: matrix B' -> byte array packed_Bp */
    frodo_pack(packed_Bp, FRODO_PACKED_B_BYTES, Bp, FRODO_NBAR * FRODO_N);

    /* Convert: b (matrix B as a byte array) -> matrix B */
    frodo_unpack(B, FRODO_N * FRODO_NBAR, packed_B, FRODO_PACKED_B_BYTES);

    /* Compute: V <- (S' * B + E'') */
    frodo_compute_out(V, Sp, FRODO_NBAR, FRODO_N, B, FRODO_NBAR, Epp);

    /* Compute: C <- V + Encode(u) */
    frodo_encode(encoded_u, u);
    frodo_add(C, V, encoded_u, FRODO_NBAR * FRODO_NBAR);

    /* Convert: matrix C -> byte array packed_C */
    frodo_pack(packed_C, FRODO_PACKED_C_BYTES, C, FRODO_NBAR * FRODO_NBAR);

    /* Arrange: ct <- packed_Bp || packed_C || salt */
    memcpy(ct, packed_Bp, FRODO_PACKED_B_BYTES);
    memcpy(ct + FRODO_PACKED_B_BYTES, packed_C, FRODO_PACKED_C_BYTES);
    memcpy(ct + FRODO_PACKED_B_BYTES + FRODO_PACKED_C_BYTES, salt, FRODO_SALT_BYTES);

    /* Arrange: ss_in <- packed_Bp || packed_C || salt || k */
    memcpy(ss_in, packed_Bp, FRODO_PACKED_B_BYTES);
    memcpy(ss_in + FRODO_PACKED_B_BYTES, packed_C, FRODO_PACKED_C_BYTES);
    memcpy(ss_in + FRODO_PACKED_B_BYTES + FRODO_PACKED_C_BYTES, salt, FRODO_SALT_BYTES);
    memcpy(ss_in + FRODO_PACKED_B_BYTES + FRODO_PACKED_C_BYTES + FRODO_SALT_BYTES, k,
           FRODO_SEC_BYTES);

    /* Compute: ss <- SHAKE256(ss_in)*/
    frodo_shake256(ss, FRODO_SS_BYTES, ss_in, sizeof(ss_in));

    /* Zeroize sensitive intermediates */
    memset(u, 0, sizeof(u));
    memset(digest, 0, sizeof(digest));
    memset(Sp, 0, sizeof(Sp));
    memset(Ep, 0, sizeof(Ep));
    memset(Epp, 0, sizeof(Epp));
    memset(V, 0, sizeof(V));
    memset(r_buf, 0, sizeof(r_buf));
}

/**
 * @brief Decapsulate a ciphertext to recover the shared secret.
 * 
 * Implements Frodo.Decaps per Section 8.3 of the FrodoKEM specification.
 * 
 * @param ss Output shared secret (size: FRODO_SS_BYTES bytes)
 * @param ct Input ciphertext (size: FRODO_CT_BYTES bytes)
 * @param sk Input secret key (size: FRODO_SK_BYTES bytes)
 * 
 * @note 0x96 is the domain separation byte for Frodo.Decaps per Section 8.3
 * @note S^T is unpacked little-endian per Section 8.1
 * @warning Ciphertext comparison and key selection must be constant-time
 */
void frodo_decaps(uint8_t *ss, const uint8_t *ct, const uint8_t *sk) {

    /* Parse: ct <- packed_Bp || packed_C || salt */
    const uint8_t *packed_Bp = ct;
    const uint8_t *packed_C  = ct + FRODO_PACKED_B_BYTES;
    const uint8_t *salt      = ct + FRODO_PACKED_B_BYTES + FRODO_PACKED_C_BYTES;

    /* Parse: sk <- s || pk || packed_ST || pkh */
    const uint8_t *s         = sk;
    const uint8_t *pk        = sk + FRODO_SEC_BYTES;
    const uint8_t *seed_A    = pk;
    const uint8_t *packed_B  = pk + FRODO_SEED_A_BYTES;
    const uint8_t *packed_ST = sk + FRODO_SEC_BYTES + FRODO_PK_BYTES;
    const uint8_t *pkh       = sk + FRODO_SEC_BYTES + FRODO_PK_BYTES + FRODO_PACKED_B_BYTES;

    /* Small buffers - safe for the stack */
    uint8_t u_prime[FRODO_SEC_BYTES];
    uint8_t digest[FRODO_SE_BYTES + FRODO_SEC_BYTES];
    uint8_t shake_in[FRODO_SEC_BYTES + FRODO_SEC_BYTES + FRODO_SALT_BYTES];
    uint8_t domain_sep[1 + FRODO_SE_BYTES];
    uint8_t k_bar[FRODO_SEC_BYTES];
    size_t i, j;
    int ct_match;

    /* Pointers into diget for seed_se_prime and k_prime */
    uint8_t *seed_se_prime = digest;
    uint8_t *k_prime       = digest + FRODO_SE_BYTES;

    /* Large buffers - static to keep off stack */
    static uint16_t Bp[FRODO_NBAR * FRODO_N];
    static uint16_t C[FRODO_NBAR * FRODO_NBAR];
    static uint16_t ST[FRODO_NBAR * FRODO_N];
    static uint16_t S[FRODO_N * FRODO_NBAR];
    static uint16_t B[FRODO_N * FRODO_NBAR];
    static uint16_t M[FRODO_NBAR * FRODO_NBAR];
    static uint16_t W[FRODO_NBAR * FRODO_NBAR];
    static uint16_t Sp[FRODO_NBAR * FRODO_N];
    static uint16_t Ep[FRODO_NBAR * FRODO_N];
    static uint16_t Epp[FRODO_NBAR * FRODO_NBAR];
    static uint16_t Bpp[FRODO_NBAR * FRODO_N];
    static uint16_t V[FRODO_NBAR * FRODO_NBAR];
    static uint16_t Cp[FRODO_NBAR * FRODO_NBAR];
    static uint16_t encoded_u[FRODO_NBAR * FRODO_NBAR];
    static uint8_t r_buf[(2 * FRODO_N * FRODO_NBAR + FRODO_NBAR * FRODO_NBAR) * 2];
    static uint16_t r_words[2 * FRODO_N * FRODO_NBAR + FRODO_NBAR * FRODO_NBAR];
    static uint8_t packed_Bpp[FRODO_PACKED_B_BYTES];
    static uint8_t packed_Cp[FRODO_PACKED_C_BYTES];
    static uint8_t
        ss_in[FRODO_PACKED_B_BYTES + FRODO_PACKED_C_BYTES + FRODO_SALT_BYTES + FRODO_SEC_BYTES];

    /* Unpack matrices B' (Bp) and C from ciphertext (ct) */
    frodo_unpack(Bp, FRODO_NBAR * FRODO_N, packed_Bp, FRODO_PACKED_B_BYTES);
    frodo_unpack(C, FRODO_NBAR * FRODO_NBAR, packed_C, FRODO_PACKED_C_BYTES);

    /* Unpack S^T from secret key (sk) in little-endian */
    frodo_unpack_le16(ST, packed_ST, FRODO_NBAR * FRODO_N);

    /* Transpose S^T to get matrix S */
    for (i = 0; i < FRODO_N; i++) {
        for (j = 0; j < FRODO_NBAR; j++) {
            S[i * FRODO_NBAR + j] = ST[j * FRODO_N + i];
        }
    }

    /* Compute: M <- (C - B' * S) */
    memset(M, 0, sizeof(M)); // zero init `M`
    frodo_compute_out(W, Bp, FRODO_NBAR, FRODO_N, S, FRODO_NBAR, M);
    frodo_sub(M, C, W, FRODO_NBAR * FRODO_NBAR);

    /* Compute: u' <- Decode(M) */
    frodo_decode(u_prime, M);

    /* Arrange: shake_in <- pkh || u' || salt */
    memcpy(shake_in, pkh, FRODO_SEC_BYTES);
    memcpy(shake_in + FRODO_SEC_BYTES, u_prime, FRODO_SEC_BYTES);
    memcpy(shake_in + FRODO_SEC_BYTES + FRODO_SEC_BYTES, salt, FRODO_SALT_BYTES);

    /* Compute: digest (seed_SE' || k') <- SHAKE256(shake_in) */
    frodo_shake256(digest, sizeof(digest), shake_in, sizeof(shake_in));

    /* Arrange: 0x96 (domain_sep) || seed_se_prime */
    domain_sep[0] = 0x96;
    memcpy(domain_sep + 1, seed_se_prime, FRODO_SE_BYTES);

    /* Compute: r' (r_buf) <- SHAKE256(0x96 || seed_se_prime) */
    frodo_shake256(r_buf, sizeof(r_buf), domain_sep, sizeof(domain_sep));

    /* Convert: r' (r_buf) bytes -> little-endian uint16_t words */
    for (i = 0; i < 2 * FRODO_N * FRODO_NBAR + FRODO_NBAR * FRODO_NBAR; i++) {
        r_words[i] = (uint16_t)r_buf[2 * i] | ((uint16_t)r_buf[2 * i + 1] << 8);
    }

    /* Re-sample: S' (Sp), E' (Ep), and E'' (Epp) */
    frodo_sample_matrix(Sp, r_words, FRODO_NBAR * FRODO_N);
    frodo_sample_matrix(Ep, r_words + FRODO_NBAR * FRODO_N, FRODO_NBAR * FRODO_N);
    frodo_sample_matrix(Epp, r_words + 2 * FRODO_NBAR * FRODO_N, FRODO_NBAR * FRODO_NBAR);

    /* Encrypt via Computing:
        B'' <- S' * A + E'
        C' <- S' * B + E'' + Encode(u')
    */
    // Compute: S' * A + E'
    frodo_mul_add_spa_plus_e(Bpp, Sp, Ep, seed_A);
    // Convert: packed_B (bytes) -> B (matrix, n x nbar)
    frodo_unpack(B, FRODO_N * FRODO_NBAR, packed_B, FRODO_PACKED_B_BYTES);
    // Compute: S' * B + E''
    frodo_compute_out(V, Sp, FRODO_NBAR, FRODO_N, B, FRODO_NBAR, Epp);
    // Convert: u' (bytes) -> encoded_u (matrix nbar x nbar)
    frodo_encode(encoded_u, u_prime);
    // Compute: C' <- V + encoded_u
    frodo_add(Cp, V, encoded_u, FRODO_NBAR * FRODO_NBAR);

    /* Convert: B'' (matrix) -> packed_Bpp (bytes) */
    frodo_pack(packed_Bpp, FRODO_PACKED_B_BYTES, Bpp, FRODO_NBAR * FRODO_N);

    /* Convert: C' (matrix) -> packed_Cp (bytes) */
    frodo_pack(packed_Cp, FRODO_PACKED_C_BYTES, Cp, FRODO_NBAR * FRODO_NBAR);

    /* Compare re-encrypted ciphertext against received ciphertext (constant-time) */
    ct_match = frodo_ct_verify(packed_Bp, packed_Bpp, FRODO_PACKED_B_BYTES);
    ct_match |= frodo_ct_verify(packed_C, packed_Cp, FRODO_PACKED_C_BYTES);

    /*
     * Constant-time key selection (IND-CCA2 implicit rejection):
     *     
     *   ct_match == 0: ciphertexts match -> k_bar = k_prime (legitimate ss)
     *   
     *   ct_match != 0: ciphertexts differ -> k_bar = s (implicit rejection)
     *
     * Return a pseudorandom ss derived from s instead of an error prevents
     * an adversary from learning whether or not the decapsulation was successful,
     * preventing information about the secret key from being leaked.
     * 
     * See: FrodoKEM Preliminary Standardization Proposal, Section 8.3
     */
    frodo_ct_select(k_bar, s, k_prime, FRODO_SEC_BYTES, ct_match);

    /* Arrange: ss_in <- packed_Bp || packed_C || salt || k_bar */
    memcpy(ss_in, packed_Bp, FRODO_PACKED_B_BYTES);
    memcpy(ss_in + FRODO_PACKED_B_BYTES, packed_C, FRODO_PACKED_C_BYTES);
    memcpy(ss_in + FRODO_PACKED_B_BYTES + FRODO_PACKED_C_BYTES, salt, FRODO_SALT_BYTES);
    memcpy(ss_in + FRODO_PACKED_B_BYTES + FRODO_PACKED_C_BYTES + FRODO_SALT_BYTES, k_bar,
           FRODO_SEC_BYTES);

    /* 
     * Compute: ss <- SHAKE256(ss_in) 
     * Produces real shared secret if ct_match == 0
     */
    frodo_shake256(ss, FRODO_SS_BYTES, ss_in, sizeof(ss_in));

    /* Zeroize sensitive intermediate values */
    memset(ST, 0, sizeof(ST));
    memset(S, 0, sizeof(S));
    memset(M, 0, sizeof(M));
    memset(u_prime, 0, sizeof(u_prime));
    memset(digest, 0, sizeof(digest));
    memset(Sp, 0, sizeof(Sp));
    memset(Ep, 0, sizeof(Ep));
    memset(Epp, 0, sizeof(Epp));
    memset(V, 0, sizeof(V));
    memset(k_bar, 0, sizeof(k_bar));
    memset(r_buf, 0, sizeof(r_buf));
}
